### ISSUE TITLE
Release code

### ISSUE THREAD

**Issue by lingtengqiu** [Human-VDM/Human-VDM#1]
good work.
When you plan to release your code?

**Comment by ahmadmustafaanis** [comment]
+1

**Comment by silence-tang** [comment]
+1

**Comment by Haodong-Yan** [comment]
+1

**Comment by gt732** [comment]
any update

**Comment by aviralchharia** [comment]
Hi, Thanks for the interest in our project! The study is currently under-review and we will be open-sourcing the code after acceptance
